#cloud-config
# Cloud config for application servers

runcmd:
  # Install docker
  - curl -sSL https://get.docker.com/ | sudo sh
  # Pull the image
  - sudo docker pull joostrovers/mcma-ec2-transform-service > /var/log/docker-install.log
  # Run docker
  - sudo docker run -d -e ServicesUrl=${services_url} -e ServicesAuthType=${services_auth_type} -p 80:8080 joostrovers/mcma-ec2-transform-service > /var/log/docker-run.log